# Generated by Django 4.1.7 on 2023-02-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0003_savedata_alter_uploadimage_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveData',
        ),
    ]
